# Use an official Python runtime as a parent image
# Desbloquear la adecuada
#FROM python:2.7-slim
FROM python:3.6-slim


# Set the working directory to /app
WORKDIR /app





# Install any needed packages specified in requirements.txt
RUN pip install tensorflow
RUN pip install keras

RUN pip install numpy
RUN pip install SciPy

RUN pip install scikit-learn==0.20
RUN pip install Hyperas


