# Use an official Python runtime as a parent image
FROM python:2.7-slim

RUN mkdir /app

# Set the working directory to /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
RUN pip install baytune


